class TestBasePage(object):
    # Variables
    _URL = "https://demoqa.com/"
    _TITLE = "DEMOQA"
    _PAGE_TITLE = "Practice Form"
    _FORM_TITLE = "Student Registration Form"
    _FIRST_NAME = "John"
    _LAST_NAME = "Doe"
    _EMAIL = "b@b"
    _GENDER = "Male"
    _YEAR = "2000"
    _DATE_OF_BIRTH = "Choose Saturday, November 4th,"
    _SUBJECT_1 = "Computer"
    _SUBJECT_2 = "Eng"
    _SPORTS = "Sports"
    _READING = "Reading"
    _MUSIC = "Music"
    _ADDRESS = "Jonquil, Grandchild Center, Big Stream Avenue Shishli/İstanbul"
    _STATE = "Haryana"
    _CITY = "Panipat"
